# diction

In [1]:
dist={'Key1':12,'Key2':90}

In [2]:
dist['Key1']

12

# Set

In [2]:
S={1,1,2,2,3,3}

In [3]:
S.add(5)

In [4]:
S

{1, 2, 3, 5}

In [5]:
range(9)

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
a=(1,8,0)

In [7]:
a

(1, 8, 0)

In [8]:
a(1)

TypeError: 'tuple' object is not callable

In [9]:
a[0]

1

In [10]:
a[0]=9

TypeError: 'tuple' object does not support item assignment

In [11]:
q=range(9)

In [13]:
q.append(1)

In [14]:
q

[0, 1, 2, 3, 4, 5, 6, 7, 8, 1]

In [15]:
q.append[[1,1,1]]

TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'

In [16]:
q1=list(range(9))

In [17]:
[num**2 for num in [1,2,3,4]]

[1, 4, 9, 16]

# Printing Sth is different from return Sth

In [18]:
def my_func(name='Default Name'):
    print ('Hello '+name)

In [20]:
my_func('Damon')

Hello Damon


In [21]:
def square(num):
    """
    This is a docstring 
    can go multiple lines.
    This function squrares a number.
    """
    return num**2

In [22]:
output=square(2)

In [23]:
output

4

In [24]:
def times2(var):
    return var*2

In [25]:
times2(5)

10

In [57]:
seq=range(15)+np.ones(15)

In [56]:
seq

array([1., 2., 3., 4., 5.])

In [38]:
import numpy as np

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [41]:
t=lambda var:var**2

In [42]:
t(6)

36

In [50]:
list(map(times2,seq))

[2.0, 4.0, 6.0, 8.0, 10.0]

# filter function

In [58]:
list(filter(lambda num:num%4==0,seq))

[4.0, 8.0, 12.0]

In [59]:
s='hello my name is Sam'

# Tab after dot give out a list of function

In [60]:
s.lower()

'hello my name is sam'

In [61]:
s.upper()

'HELLO MY NAME IS SAM'

In [62]:
s.split()

['hello', 'my', 'name', 'is', 'Sam']

In [63]:
tweet='Go Sports! #Sports'

In [66]:
tweet.split('#')

['Go Sports! ', 'Sports']

In [67]:
tweet.split('#')[1]

'Sports'

In [68]:
d

NameError: name 'd' is not defined

In [69]:
d={'k1':1,'k2':2}

In [70]:
d.keys()

['k2', 'k1']

In [71]:
d.items()

[('k2', 2), ('k1', 1)]

In [72]:
d.values()

[2, 1]

In [73]:
'x'in ['x','y','z']

True

# tuple unpacking

In [75]:
x=[(1,2),(3,4),(5,6)]

In [76]:
for (a,b) in x:
    print b

2
4
6
